### ISSUE TITLE
command not found in Windows Subsystem for Linux (WSL)

### ISSUE THREAD

**Issue by name01019** [nlscc/samloader#11]
I am using Ubuntu 18.04 on Windows Subsystem for Linux (WSL)

I ran the following commands and it successfully installed samloader
```
sudo apt install python3-pip
pip3 install git+https://github.com/nlscc/samloader.git
```
However, when I run `samloader checkupdate GT-I8190N BTU`, it gives me
**samloader: command not found**

I tried `pip3 samloader` as well, but that didn't work

Can you help?

Apologies, I am a complete noob. Is this a WSL quirk that prevents command recognition after pip3 installs?

**Comment by name01019** [comment]
I found a workaround. For anyone who is reading this with this problem, here it is

I ran `find / -name "samloader"` and found that the package was located in /home/ubuntu/.local/bin/samloader

I then ran `/home/ubuntu/.local/bin/samloader checkupdate GT-I8190N BTU`, which works

Not sure if there's a way to copy the command to a directory that WSL uses by default to find commands. Would love your input. Thanks!

**Comment by Tkkg1994** [comment]
The same happens on windows with powershell. There is no link between the installed package and the system wide usage. Not on windows nor on linux it seems

**Comment by nlscc** [comment]
This isn't an issue with samloader, this is because pip installs into a local directory (usually `.local/bin`) by default, and you will notice this happens with any package that you install via pip. The solution would be to change the path to include this. For example, on GNU/Linux:
```bash
export PATH="$HOME/.local/bin:$PATH"
```
