### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'text'

### ISSUE THREAD

**Issue by Martyn911** [nlscc/samloader#18]
## Description
Error AttributeError: 'NoneType' object has no attribute 'text'

## Reproduction Steps
samloader -m SM-T510 -r ITV decrypt -v T510XXU3BTH4/T510OXM3BTH4/T510XXU3BTH4/T510XXU3BTH4 -V 4 -i ./test/SM-T510_1_20200911140634_20syc35c92_fac.zip.enc4 -o ./test/SM-T510_1_20200911140634_20syc35c92_fac.zip

## Output
Traceback (most recent call last):
  File "/home/serg/.local/bin/samloader", line 11, in <module>
    load_entry_point('samloader==0.2', 'console_scripts', 'samloader')()
  File "/home/serg/.local/lib/python3.6/site-packages/samloader/main.py", line 58, in main
    key = getkey(args.fw_ver, args.dev_model, args.dev_region)
  File "/home/serg/.local/lib/python3.6/site-packages/samloader/crypt.py", line 22, in getv4key
    logicval = root.find("./FUSBody/Put/LOGIC_VALUE_FACTORY/Data").text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by ben-xD** [comment]
Not sure why you closed this @nlscc. I had the same issue. I think this is a regression, since it works in the older version available here/ forked by https://github.com/ianmacd/samloader @ianmacd

**Comment by nlscc** [comment]
@ben-xD can you post reproduction steps and the stacktrace? The original command still works for me at master.

**Comment by ben-xD** [comment]
Hi @nlscc, sure

I was using your application for my Samsung S9:
1. `samloader -m SM-G960F -r EVR checkupdate`: Outputs `G960FXXSDFTL1/G960FOXMDFTL1/G960FXXSDFTL1/G960FXXSDFTL1`
2. `samloader -m SM-G960F -r BTU download -v G960FXXSDFTL1/G960FOXMDFTL1/G960FXXSDFTL1/G960FXXSDFTL1 -O .`

3. `samloader -m SM-G960F -r BTU decrypt -v G960FXXSDFTL1/G960FOXMDFTL1/G960FXXSDFTL1/G960FXXSDFTL1 -V 4 -i downloaded_file.zip.enc4 -o downloaded_file.zip` (Please change `downloaded_file` to the file that was downloaded)

The error happens in Step 3, decryption

**Comment by nlscc** [comment]
Those commands seem to work for me, @ben-xD. Can you please check that you're using the latest version? Try `pip3 install --upgrade git+https://github.com/nlscc/samloader.git`. Otherwise can you post what exactly the error you are getting is?
