### ISSUE TITLE
Unable to correctly decrypt some firmware packages

### ISSUE THREAD

**Issue by Martyn911** [nlscc/samloader#19]
## Description
Zip archive broken

## Reproduction Steps
# /home/serg/.local/bin/samloader -m SM-A730F -r THL download -v A730FXXU3BRH1/A730FOLM3BRH1/A730FXXU3BRH1/A730FXXU3BRH1 -M -O ./
downloading SM-A730F_1_20200605114705_3cp4i4770e_fac.zip.enc4
MD5: 9d8bf89f23e10fa27f22a1d3f6a46fbf
[################################] 50533/50533 - 00:08:23

# /home/serg/.local/bin/samloader -m SM-A730F -r THL decrypt -v A730FXXU3BRH1/A730FOLM3BRH1/A730FXXU3BRH1/A730FXXU3BRH1 -V 4 -i SM-A730F_1_20200605114705_3cp4i4770e_fac.zip.enc4 -o SM-A730F_1_20200605114705_3cp4i4770e_fac.zip
[################################] 808524/808524 - 00:00:32

# unzip -t SM-A730F_1_20200605114705_3cp4i4770e_fac.zip
Archive:  SM-A730F_1_20200605114705_3cp4i4770e_fac.zip
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of SM-A730F_1_20200605114705_3cp4i4770e_fac.zip or
        SM-A730F_1_20200605114705_3cp4i4770e_fac.zip.zip, and cannot find SM-A730F_1_20200605114705_3cp4i4770e_fac.zip.ZIP, period.

**Comment by nlscc** [comment]
Temporary fix (note the different version):
```
samloader -m SM-A730F -r THL decrypt -v A730FXXU7CTE1/A730FOLM7CTE2/A730FXXU7CTE1/A730FXXU7CTE1 -V 4 -i SM-A730F_1_20200605114705_3cp4i4770e_fac.zip.enc4 -o SM-A730F_1_20200605114705_3cp4i4770e_fac.zip
```
I think I found the issue and am working on a permanent one though
