### ISSUE TITLE
Support test xml (beta downloads)

### ISSUE THREAD

**Issue by SanderGit** [nlscc/samloader#20]
## Description
Support downloading beta versions

## Background
It would be great if beta versions could be downloaded.
See e.g. https://forum.xda-developers.com/galaxy-s10/how-to/g973f-75f-oneui-3-0-testing-ospserver-t4176545
This means that e.g. this xml file would need to be parsed:
https://fota-cloud-dn.ospserver.net/firmware/DBT/SM-G973F/version.test.xml

**Comment by amaterasushen** [comment]
> ## Descrição
> Suporte para download de versões beta
> 
> ## Fundo
> Seria ótimo se as versões beta pudessem ser baixadas.
> Veja, por exemplo, https://forum.xda-developers.com/galaxy-s10/how-to/g973f-75f-oneui-3-0-testing-ospserver-t4176545
> Isso significa que, por exemplo, este arquivo xml precisaria ser analisado:
> https://fota-cloud-dn.ospserver.net/firmware/DBT/SM-G973F/version.test.xml

managed to find a way to download via xml?

**Comment by TheAirBlow** [comment]
It's yet unknown how to download these betas. They use a completely different format which needs to be reverse-engineered.

**Comment by yEsPaP** [comment]
do you have the device?

when beta comes out download&setup charles http proxy and connect to wifi hotspot hosted from pc also enable ssl decryption support for the samsung fota webpage

you will get the request the phone sends

**Comment by nlscc** [comment]
afaik FUS / SmartSwitch can't download beta updates, only certain release versions. so this is impossible unless someone can prove it wrong
