### ISSUE TITLE
Can't download firmware : 403 error

### ISSUE THREAD

**Issue by MK73DS** [nlscc/samloader#27]
## Description
I first need to thank you for this tool, I discovered it today precicely because of this error : using either Frija and SamFirm, I have a 403 error when downloading, so I searched for another tool and hoped this one could solve that. But the problem is still the same : I can check for new updates but not download them because of a 403 error

## Background

Reproducing the issue is quite simple, just try downloading a firmware (for a friend's device, a french (XEF) Galaxy S9 (SM-G960F)).
```
>samloader -m SM-G960F -r XEF checkupdate
G960FXXUCFTJ2/G960FOXMCFTJ2/G960FXXUCFTJ1/G960FXXUCFTJ2

>samloader -m SM-G960F -r XEF download -v G960FXXUCFTJ2/G960FOXMCFTJ2/G960FXXUCFTJ1/G960FXXUCFTJ2 -O FW
downloading SM-G960F_2_20201012211333_osd1wkweg9_fac.zip.enc4
Traceback (most recent call last):
  File "C:\Users\XX\AppData\Local\Programs\Python\Python38-32\Scripts\samloader-script.py", line 11, in <module>
    load_entry_point('samloader==0.2', 'console_scripts', 'samloader')()
  File "c:\users\XX\appdata\local\programs\python\python38-32\lib\site-packages\samloader\main.py", line 45, in main
    r = client.downloadfile(path+filename, dloffset)
  File "c:\users\XX\appdata\local\programs\python\python38-32\lib\site-packages\samloader\fusclient.py", line 34, in downloadfile
    r.raise_for_status()
  File "c:\users\XX\appdata\local\programs\python\python38-32\lib\site-packages\requests\models.py", line 941, in raise_for_status 
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://cloud-neofussvr.sslcs.cdngc.net/NF_DownloadBinaryForMass.do?file=%2Fneofus%2F910%2FSM-G960F_2_20201012211333_osd1wkweg9_fac.zip.enc4
```

Note : the example usage in the Readme leads to the same error.

**Comment by goofwear** [comment]
I got the same error last night. I tried Sam loader Sam firm continued and Frija.
I checked the network traffic and I noticed it wasn't getting a session ID it was blank 
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://cloud-neofussvr.sslcs.cdngc.net/NF_DownloadBinaryForMass.do?file=%2Fneofus%2F911%2FSM-G975U_1_20201013033404_6o8s0837ue_fac.zip.enc4

**Comment by roynatech2544** [comment]
Maybe samsung disabled the server access from outside?

**Comment by SanderGit** [comment]
The 1.4.3 build of Frija seems to have solved the issue so don't give up hope yet. Either @nlscc or @ianmacd can fix this for sure.

**Comment by ivanmeler** [comment]
I was looking into recent response changes from samsung and decided to implement them into SamFirm, After some messing around i got it working again, So this might be useful to @nlscc here is the fix https://github.com/ivanmeler/SamFirm_Reborn/commit/959e6306ab887bba8747500d3893f20c018d95f0

Would implement it myself but python usualy gives me headache haha anyway great tool, It really helps me when working on aosp as i dont have to download firmwares from my windows pc and transfer them

**Comment by BeatLink** [comment]
Eagerly awaiting a fix on this issue

**Comment by ianmacd** [comment]
> I was looking into recent response changes from samsung and decided to implement them into SamFirm, After some messing around i got it working again, So this might be useful to @nlscc here is the fix [ivanmeler/SamFirm_Reborn@959e630](https://github.com/ivanmeler/SamFirm_Reborn/commit/959e6306ab887bba8747500d3893f20c018d95f0)

I'm happy to submit a pull request to the author, but I don't see what the commit in question actually changes about how HTTP requests are sent.

I'm not a C# programmer, but the code is easy to read. The patch appears to be a different way of doing the same thing, namely the setting of JSESSIONID in a cookie to subsequent HTTP requests. Obviously, if this fixes SamFirm, then I'm missing something when I read the code, but it appears to do the same thing as the code it replaces.

Can you describe what changed on Samsung's end? Then it should be trivial to fix in the Python code.

**Comment by corsicanu** [comment]
> > I was looking into recent response changes from samsung and decided to implement them into SamFirm, After some messing around i got it working again, So this might be useful to @nlscc here is the fix [ivanmeler/SamFirm_Reborn@959e630](https://github.com/ivanmeler/SamFirm_Reborn/commit/959e6306ab887bba8747500d3893f20c018d95f0)
> 
> I'm happy to submit a pull request to the author, but I don't see what the commit in question actually changes about how HTTP requests are sent.
> 
> I'm not a C# programmer, but the code is easy to read. The patch appears to be a different way of doing the same thing, namely the setting of JSESSIONID in a cookie to subsequent HTTP requests. Obviously, if this fixes SamFirm, then I'm missing something when I read the code, but it appears to do the same thing as the code it replaces.
> 
> Can you describe what changed on Samsung's end? Then it should be trivial to fix in the Python code.

Add some debug printing in Samfirm code to see exactly what's changed. The code @ivanmeler added does same thing as the old one did but in a new environment in which the old code doesn't work anymore.

**Comment by ianmacd** [comment]
> Add some debug printing in Samfirm code to see exactly what's changed. The code @ivanmeler added does same thing as the old one did but in a new environment in which the old code doesn't work anymore.

I don't have a Windows build environment, so that's not a practical option for me.

If the new code did exactly the same thing as the old code, however, it still wouldn't work, so there **is** a difference, even if it's not apparent to me from looking at the code here.

Perhaps the `samloader` author will have time to look into the issue. I have spent a few hours on it myself, but having no familiarity with what a FUS exchange looked like in the old scenario, it's hard for me to play spot the difference now in the new one.

**Comment by nlscc** [comment]
god, I really don't have the energy to fix this. Mental health is terrible and I can't see myself focusing on this long enough. It would be great if somebody could look into this. It seems to be an issue on the separate cloud server (cloud-neofussvr.sslcs.cdngc.net)
These functions are all based on the file 'SmartSwitch.app/Contents/Resources/SAMSUNG FUS Agent.bundle/Contents/Resources/Comm.bundle/Contents/MacOS/Comm' from the MacOS version of Smart Switch if that helps.
might want to download the code quickly in case I end up deleting everything again haha

**Comment by nlscc** [comment]
I'm so sorry for everything, I should probably fix my own program but I can't even do that. I'm sure this issue is hopefully fixable though

**Comment by olipayne** [comment]
> I'm so sorry for everything, I should probably fix my own program but I can't even do that. I'm sure this issue is hopefully fixable though

Hey, don't worry about fixing every issue. That's why you've open sourced this repo in the first place. Take care of yourself and your mental health before anything else. If someone else desperately needs this then they'll find a way to get it working themselves. I for one am looking forward to digging into this issue this weekend if it's not already solved! 

Please don't delete the repo, even if you never work on it again! It should be remembered that this is where it started 💙

**Comment by ianmacd** [comment]
> I'm so sorry for everything, I should probably fix my own program but I can't even do that. I'm sure this issue is hopefully fixable though

No worries, man.

You've been generous enough to give us the code. If you are unable to work on it or just don't feel like it, the rest of us can take it from here.

**Comment by ericswpark** [comment]
That is one ridiculous bug lol. Thank you @topjohnwu for finding the fix

**Comment by ianmacd** [comment]
Often the fix is just a single line of code. Sometimes it's just a single character.

The SamFirm fix was a red herring here, because although SamFirm and `samloader` broke at the same time, they broke for different reasons.

Thanks, @topjohnwu.

**Comment by nlscc** [comment]
Thank you guys so much (:

**Comment by IgorGanapolsky** [comment]
I am still experiencing this error in 2022:
<img width="938" alt="Screenshot 2022-11-28 at 11 30 40 AM" src="https://user-images.githubusercontent.com/201209/204330540-f1a7d77d-9044-4068-9c3b-174351b6d368.png">
