### ISSUE TITLE
Authorization failed!

### ISSUE THREAD

**Issue by ltquang3** [nlscc/samloader#36]
## Description
Cannot download firmware

## Reproduction Steps
Searching and download firmware for SM-G960N - KTC, the latest version

## Output
SamFirm v1.4.2
Checking firmware for SM-G960N/KTC/G960NKSU3FTK1/G960NOKR3FTK1/G960NKOU3FTJ2/G960NKSU3FTK1
Error UpdateCheck(): Could not send BinaryInform. Status code (200/401)
Error CheckHtmlXmlStatus(): Authorization failed.
Checking firmware for SM-G960N/KTC/G960NKSU2CSJ1/G960NOKR2CSJ1/G960NKOU2CSI1/G960NKSU2CSJ1
Error UpdateCheck(): Could not send BinaryInform. Status code (200/401)
Error CheckHtmlXmlStatus(): Authorization failed.
Error UpdateCheckAuto(): Could not fetch info for SM-G960N/KTC. Please check the input data.

## Environment
Windows 10

**Comment by nlscc** [comment]
Um, I don't think you're in the right place. This is samloader and not SamFirm. But if SamFirm doesn't work you could always try this tool (:
