### ISSUE TITLE
Any way to determine which type of encryption is needed?

### ISSUE THREAD

**Issue by smartass08** [nlscc/samloader#4]
As the title suggests, I was thinking to use your project with a telegram bot -  so any way to determine the encryption between these two (enc2 vs enc4)? Btw awesome work making this!

**Comment by nlscc** [comment]
I just added support for downloading to a directory (27a057d) so you should be able to do that and then check the filename (it is also printed to stdout).
The extension is either .enc2 or .enc4, which should tell you the encryption type.

**Comment by smartass08** [comment]
Thanks!
