### ISSUE TITLE
Automatic decryption error

### ISSUE THREAD

**Issue by 2ndMessiah** [nlscc/samloader#41]
Tested the -D argument by downloading a SM-G981U firmware.Error bumps out like this:

>samloader -m SM-G981U1 -r XAA download -v G981U1UES1CUA2/G981U1OYM1CUA2/G981U1UES1CUA2/G981U1UES1CUA2 -D -O /gdrive/MyDrive/uupdump/

downloading SM-G981U1_1_20210115182235_ut9k755kqx_fac.zip.enc4
[################################] 86929/86929 - 00:07:36
decyrpting /gdrive/MyDrive/uupdump/SM-G981U1_1_20210115182235_ut9k755kqx_fac.zip.enc4
Traceback (most recent call last):
  File "/usr/local/bin/samloader", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/samloader/main.py", line 62, in main
    getkey = crypt.getv2key if filename.endswith(".enc2") else crypt.getenc4key
AttributeError: module 'samloader.crypt' has no attribute 'getenc4key'

Check crypt.py, that method should be getv4key.

**Comment by nlscc** [comment]
sorry im stupid and forgot to test code (: should be fixed now

**Comment by 2ndMessiah** [comment]
> sorry im stupid and forgot to test code (: should be fixed now

U're doing it well mane!
