### ISSUE TITLE
When downloading firmware for SM-T970N (Samsung Galaxy Tablet S7 Plus Wifi XAR, error returned 403 client error, forbidden.  

### ISSUE THREAD

**Issue by vanquishsecurity** [nlscc/samloader#43]
## Description
When downloading firmware for SM-T970N (Samsung Galaxy Tablet S7 Plus Wifi XAR, error returned 403 client error, forbidden.  

## Reproduction Steps

samloader -m SM-T970N -r XAR checkupdate

## Output

samloader -m SM-T970N -r XAR checkupdate
Traceback (most recent call last):
  File "/home/vanquish/.local/bin/samloader", line 8, in <module>
    sys.exit(main())
  File "/home/vanquish/.local/lib/python3.8/site-packages/samloader/main.py", line 70, in main
    print(versionfetch.getlatestver(args.dev_model, args.dev_region))
  File "/home/vanquish/.local/lib/python3.8/site-packages/samloader/versionfetch.py", line 11, in getlatestver
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://fota-cloud-dn.ospserver.net/firmware/XAR/SM-T970N/version.xml

## Environment

vanquish@Vanquish-pc:~/.local/bin$ pwd
/home/vanquish/.local/bin

vanquish@Vanquish-pc:~/.local/bin$ python3 -V
Python 3.8.5

/usr/bin/python3.8 samloader -m SM-T970N -r XAR checkupdate
Traceback (most recent call last):
  File "samloader", line 8, in <module>
    sys.exit(main())
  File "/home/vanquish/.local/lib/python3.8/site-packages/samloader/main.py", line 70, in main
    print(versionfetch.getlatestver(args.dev_model, args.dev_region))
  File "/home/vanquish/.local/lib/python3.8/site-packages/samloader/versionfetch.py", line 11, in getlatestver
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://fota-cloud-dn.ospserver.net/firmware/XAR/SM-T970N/version.xml

**Comment by vanquishsecurity** [comment]
I figured it out from samfirm site. I was using product code SM-T970N, instead of SM-T970.

https://samfw.com/firmware/SM-T970/XAR/T970XXU1BUAA

usr/bin/python3.8 samloader -m SM-T970 -r XAR checkupdate
T970XXU1BUAA/T970OXM1BUAA/T970XXU1BUAA/T970XXU1BUAA

**Comment by vanquishsecurity** [comment]
/usr/bin/python3.8 /home/vanquish/.local/bin/samloader -m SM-T970 -r XAR checkupdate
T970XXU1BUAA/T970OXM1BUAA/T970XXU1BUAA/T970XXU1BUAA

/usr/bin/python3.8 /home/vanquish/.local/bin/samloader -m SM-T970 -r XAR download -v T970XXU1BUAA/T970OXM1BUAA/T970XXU1BUAA/T970XXU1BUAA -O .

downloading SM-T970_1_20210121210134_84ml313a23_fac.zip.enc4
[################################] 109073/109073 - 00:10:04



/usr/bin/python3.8 /home/vanquish/.local/bin/samloader -m SM-T970 -r XAR decrypt -v T970XXU1BUAA/T970OXM1BUAA/T970XXU1BUAA/T970XXU1BUAA -V 4 -i SM-T970_1_20210121210134_84ml313a23_fac.zip.enc4 -o SM-T970_1_20210121210134_84ml313a23_fac.zip

[################################] 1745162/1745162 - 00:00:27


unzip SM-T970_1_20210121210134_84ml313a23_fac.zip
Archive:  SM-T970_1_20210121210134_84ml313a23_fac.zip
  inflating: BL_T970XXU1BUAA_CL20748183_QB37638525_REV00_user_low_ship_MULTI_CERT.tar.md5  
  inflating: AP_T970XXU1BUAA_CL20748183_QB37638525_REV00_user_low_ship_MULTI_CERT_meta_OS11.tar.md5  
  inflating: HOME_CSC_OMC_OXM_T970OXM1BUAA_CL20748183_QB37638525_REV00_user_low_ship_MULTI_CERT.tar.md5  
  inflating: CSC_OMC_OXM_T970OXM1BUAA_CL20748183_QB37638525_REV00_user_low_ship_MULTI_CERT.tar.md5

**Comment by apeterson26** [comment]
samloader -m SM-T970N -r XAR checkupdate

**Comment by asdsadsaasd12312132** [comment]
I have the same problem with

`samloader -m SM-G9777B -r TEL checkupdate`

Error:
```

C:\Users\ssd1231231312>samloader -m SM-G9777 -r TEL checkupdate
Traceback (most recent call last):
  File "C:\Python39\Scripts\samloader-script.py", line 33, in <module>
    sys.exit(load_entry_point('samloader==0.3', 'console_scripts', 'samloader')())
  File "c:\python39\lib\site-packages\samloader\main.py", line 70, in main
    print(versionfetch.getlatestver(args.dev_model, args.dev_region))
  File "c:\python39\lib\site-packages\samloader\versionfetch.py", line 11, in getlatestver
    r.raise_for_status()
  File "c:\python39\lib\site-packages\requests\models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://fota-cloud-dn.ospserver.net/firmware/TEL/SM-G9777/version.xml
```

**Comment by TheAirBlow** [comment]
Can you close the issue then?
