### ISSUE TITLE
Where can I get the HOME_CSC file?

### ISSUE THREAD

**Issue by calibs** [nlscc/samloader#44]
I thank you for making this downloader alternative. Just to ask, why HOME_CSC file is missing in the downloaded firmware?

**Comment by KUKARAF** [comment]
@calibs  Samloader downloads the encrypted OTA update directly from Samsung servers  (fota-cloud-dn.ospserver.net) and allows you to decrypt it. The content of the file is therefore still determined by Samsung and has nothing to do with samloader. 

I believe this issue can be closed.

**Comment by calibs** [comment]
@KUKARAF I wonder where do firmware website like Sammobile get their CSC files.

**Comment by calibs** [comment]
I get it now. HOME_CSC files are included on firmware but there are other models that do not have it. Closing this issue now.
