### ISSUE TITLE
Refactor code and add docstrings

### ISSUE THREAD

**Issue by Nemris** [nlscc/samloader#46]
## Description
Good day! First of all - nice work with reversing those libraries. I tested the tool just today, and it worked perfectly on Arch.

Now then - I noticed your code could use some documentation, especially for the more obscure crypto-related parts. This is easily achieved with Python's docstrings.
Is it something in the roadmap, or would you accept PRs?

Furthermore, I spotted some Python antipatterns in your code - not catching some exceptions, raising `Except` directly and using `assert` in production code come to mind.
Would you accept PRs to deal with that?

## Background
Self-documenting code, descriptive error messages and usage of common Python idioms are all useful to ensure code clarity and possibly reduce the amount of bugs.

**Comment by nlscc** [comment]
thanks but i already did a lot of that myself (: if you want to help i could use some cleaning up main.py though!

**Comment by Nemris** [comment]
Quite a fine job, if I may - and I'll pay a look at `main.py` as soon as I get some time!
