### ISSUE TITLE
Decrypt command not working

### ISSUE THREAD

**Issue by n0rder** [nlscc/samloader#48]
## Description
I cant decrypt a package downloaded with frija, please see below.
https://prnt.sc/13o1gk8

## Reproduction Steps

- Installed samloader using pip.

- Attempted to run the command: `samloader -m SM-N975F -r XEU decrypt -v N975FXXU7FUE3/N975FOXM7FUE3/N975FXXU7FUE1 -V 4 -i SM-N975F_2_20210507162507_s8yzxei1fo_fac.zip.enc4 -o SM-N975F_2_20210507162507_s8yzxei1fo_fac.zip`.

## Output
`Traceback (most recent call last):
  File "C:\Python39\Scripts\samloader-script.py", line 33, in <module>
    sys.exit(load_entry_point('samloader==0.3', 'console_scripts', 'samloader')())
  File "C:\Python39\lib\site-packages\samloader\main.py", line 73, in main
    key = getkey(args.fw_ver, args.dev_model, args.dev_region)
  File "C:\Python39\lib\site-packages\samloader\crypt.py", line 23, in getv4key
    fwver = root.find("./FUSBody/Results/LATEST_FW_VERSION/Data").text
AttributeError: 'NoneType' object has no attribute 'text'`

## Environment
Python 3, Windows 10 Pro, Powershell.exe Admin Mode.

**Comment by nlscc** [comment]
`N975FXXU7FUE3/N975FOXM7FUE3/N975FXXU7FUE1` should be `N975FXXU7FUE3/N975FOXM7FUE3/N975FXXU7FUE1/N975FXXU7FUE3` (full version code)
however I will add a fix for expanding codes for users
