### ISSUE TITLE
some models use new url

### ISSUE THREAD

**Issue by yEsPaP** [nlscc/samloader#53]
## Description

Some models now use a different URL than https://fota-cloud-dn.ospserver.net/firmware/<csc>/<model>/version.xml
## Reproduction Steps

samloader -m SM-S757BL -r TFN checkupdate
## Output

```
Traceback (most recent call last):
  File "/home/henris/.local/bin/samloader", line 8, in <module>
    sys.exit(main())
  File "/home/henris/.local/lib/python3.8/site-packages/samloader/main.py", line 70, in main
    print(versionfetch.getlatestver(args.dev_model, args.dev_region))
  File "/home/henris/.local/lib/python3.8/site-packages/samloader/versionfetch.py", line 22, in getlatestver
    req.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://fota-cloud-dn.ospserver.net/firmware/TFN/SM-S757BL/version.xml
```
## Environment

python 3.9, ubuntu 20

i tried using kies3 and it finds the latest version that way, so there must be a new url where they keep the version strings.

kies3 request response: https://pastebin.com/mxcXEnmV

**Comment by hgerrald** [comment]
I switched to Kies3.0 in versionfetch.py and am still experiencing the same issue. Can you explain how you stopped seeing the 403 error?

**Comment by yEsPaP** [comment]
> I switched to Kies3.0 in versionfetch.py and am still experiencing the same issue. Can you explain how you stopped seeing the 403 error?

I just closed the issue due to no response....

It seems you can only check fota for this model using samsung knox e-fota api
