### ISSUE TITLE
Resume failed download

### ISSUE THREAD

**Issue by dmt0** [nlscc/samloader#55]
## Description
Being able resume failed download
Bonus point: restart automatically

## Background
Would be great for bad internet connections. Those images are pretty huge.

**Comment by ydaniels** [comment]
You can use -R to resume download

**Comment by dmt0** [comment]
Cool, I guess this can be marked as a documentation issue, cause I've got no idea how you found out about that.

**Comment by nlscc** [comment]
`samloader download --help`. but yeah documentation needs some improvement (:
