### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by michelle1574** [nlscc/samloader#62]
SyntaxError: Non-UTF-8 code starting with '\xb3' in file C:\Users\<user>\AppData\Local\Programs\Python\Python310\Scripts\samloader-script.py on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

**Comment by nlscc** [comment]
bestie how am I supposed to reproduce this? what did you do to get the message??
maybe your username has unicode characters? i have no idea

**Comment by michelle1574** [comment]
Yes it has. And also it has spaces
