### ISSUE TITLE
ERROR: You must give at least one requirement to install (see "pip help install")

### ISSUE THREAD

**Issue by b0xBR** [nlscc/samloader#8]
Hi!

When I try to execute command "pip3 install" it gives me this error:
ERROR: You must give at least one requirement to install (see "pip help install")

I'm using w10 20H2 + choco (which installed pip).

**Comment by nlscc** [comment]
You forgot to specify the package to install (i.e. the path of samloader). The correct syntax is ```pip3 install <path-to-samloader>```. or ```pip3 install git+https://github.com/nlscc/samloader.git```.
